name: Run Angel One Scanner Bot

on:
  workflow_dispatch:
  schedule:
    - cron: '*/2 * * * *'  # Runs every 2 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install smartapi-python python-telegram-bot pyotp

      - name: Run scanner.py
        env:
          ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
          ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
          ANGEL_PASSWORD: ${{ secrets.ANGEL_PASSWORD }}
          ANGEL_TOTP_SECRET: ${{ secrets.ANGEL_TOTP_SECRET }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python scanner.py
