name: Angel Stock Scanner

on:
  schedule:
    - cron: '*/2 3-10 * * 1-5'  # Every 2 minutes from 8:30am to 3:30pm UTC (IST 9:00am - 4:00pm)
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      ANGEL_API_KEY: ${{ secrets.ANGEL_API_KEY }}
      ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
      ANGEL_PASSWORD: ${{ secrets.ANGEL_PASSWORD }}
      ANGEL_TOTP_SECRET: ${{ secrets.ANGEL_TOTP_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Angel Stock Scanner
        run: |
          python scanner.py
