name: NSE BTST Scanner Bot

on:
  schedule:
    - cron: '*/15 3-10 * * 1-5'  # Every 15 mins (8:30 AM to 3:30 PM IST)
  workflow_dispatch:

jobs:
  run-scanner:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: pip install requests

      - name: Run BTST scanner
        run: python scanner.py
