name: NSE Scanner Bot

on:
  schedule:
    - cron: '45 3 * * 1-5'   # 09:15 AM IST
    - cron: '45 4 * * 1-5'   # 10:15 AM IST
    - cron: '45 5 * * 1-5'   # 11:15 AM IST
    - cron: '45 6 * * 1-5'   # 12:15 PM IST
    - cron: '45 7 * * 1-5'   # 01:15 PM IST
    - cron: '45 8 * * 1-5'   # 02:15 PM IST
    - cron: '45 9 * * 1-5'   # 03:15 PM IST
    - cron: '45 10 * * 1-5'  # 04:15 PM IST
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scanner
        run: python scanner.py
