name: Test Angel & Telegram

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      TELEGRAM_TOKEN:    ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID:  ${{ secrets.TELEGRAM_CHAT_ID }}
      ANGEL_API_KEY:     ${{ secrets.ANGEL_API_KEY }}
      ANGEL_CLIENT_CODE: ${{ secrets.ANGEL_CLIENT_CODE }}
      ANGEL_MPIN:        ${{ secrets.ANGEL_MPIN }}
      ANGEL_TOTP_SECRET: ${{ secrets.ANGEL_TOTP_SECRET }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Test Script
        run: python test.py
